{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Use of Python Packages\n",
    "\n",
    "Install and uninstall packages."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting polars\n",
      "  Using cached polars-1.29.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (14 kB)\n",
      "Using cached polars-1.29.0-cp39-abi3-macosx_11_0_arm64.whl (31.1 MB)\n",
      "Installing collected packages: polars\n",
      "Successfully installed polars-1.29.0\n",
      "Requirement already satisfied: databpy in /Applications/Blender.app/Contents/Resources/4.4/python/lib/python3.11/site-packages (0.0.18)\n",
      "Requirement already satisfied: numpy<2.0,>=1.24.0 in /Applications/Blender.app/Contents/Resources/4.4/python/lib/python3.11/site-packages (from databpy) (1.26.4)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.0\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49m/Applications/Blender.app/Contents/Resources/4.4/python/bin/python3.11 -m pip install --upgrade pip\u001b[0m\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.0\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49m/Applications/Blender.app/Contents/Resources/4.4/python/bin/python3.11 -m pip install --upgrade pip\u001b[0m\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import subprocess\n",
    "import sys\n",
    "subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"polars\"])\n",
    "subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"databpy\"])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found existing installation: polars 1.29.0\n",
      "Uninstalling polars-1.29.0:\n",
      "  Successfully uninstalled polars-1.29.0\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import subprocess\n",
    "import sys\n",
    "\n",
    "# non-interactive uninstall of matplotlib from Blenderâ€™s Python\n",
    "subprocess.check_call([sys.executable, \"-m\", \"pip\", \"uninstall\", \"-y\", \"polars\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2mUsing CPython 3.11.10\u001b[0m\n",
      "\u001b[2mAudited \u001b[1m1 package\u001b[0m \u001b[2min 1ms\u001b[0m\u001b[0m\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "CompletedProcess(args='UV_PYTHON=python3.11 /opt/homebrew/bin/uv pip install --prefix /Applications/Blender.app/Contents/Resources/4.3/python/ matplotlib', returncode=0)"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2025-05-14 21:14:23.002 ServerApp] 302 GET / (@127.0.0.1) 0.37ms\n",
      "[I 2025-05-14 21:14:23.003 LabApp] 302 GET /lab? (@127.0.0.1) 0.40ms\n",
      "[W 2025-05-14 21:14:23.007 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:23.007 ServerApp] 403 GET /api/kernelspecs?1747250063006 (@127.0.0.1) 1.07ms referer=None\n",
      "[W 2025-05-14 21:14:23.008 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:23.008 ServerApp] 403 GET /api/kernels?1747250063006 (@127.0.0.1) 1.53ms referer=None\n",
      "[W 2025-05-14 21:14:23.009 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:23.010 ServerApp] 403 GET /api/kernels?1747250063006 (@127.0.0.1) 0.86ms referer=None\n",
      "[W 2025-05-14 21:14:23.010 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:23.010 ServerApp] 403 GET /api/sessions?1747250063007 (@127.0.0.1) 1.10ms referer=None\n",
      "[W 2025-05-14 21:14:23.012 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:23.013 ServerApp] 403 GET /api/kernelspecs?1747250063009 (@127.0.0.1) 1.64ms referer=None\n",
      "[I 2025-05-14 21:14:27.912 ServerApp] 302 GET / (@127.0.0.1) 0.86ms\n",
      "[I 2025-05-14 21:14:27.914 LabApp] 302 GET /lab? (@127.0.0.1) 0.67ms\n",
      "[W 2025-05-14 21:14:27.920 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:27.921 ServerApp] 403 GET /api/kernelspecs?1747250067918 (@127.0.0.1) 1.17ms referer=None\n",
      "[W 2025-05-14 21:14:27.922 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:27.923 ServerApp] 403 GET /api/kernels?1747250067919 (@127.0.0.1) 1.91ms referer=None\n",
      "[W 2025-05-14 21:14:27.923 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:27.924 ServerApp] 403 GET /api/kernels?1747250067919 (@127.0.0.1) 2.54ms referer=None\n",
      "[W 2025-05-14 21:14:27.924 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:27.925 ServerApp] 403 GET /api/sessions?1747250067920 (@127.0.0.1) 3.13ms referer=None\n",
      "[W 2025-05-14 21:14:27.926 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:27.926 ServerApp] 403 GET /api/kernelspecs?1747250067921 (@127.0.0.1) 0.91ms referer=None\n",
      "[I 2025-05-14 21:14:27.941 ServerApp] 302 GET / (@127.0.0.1) 0.68ms\n",
      "[I 2025-05-14 21:14:27.943 LabApp] 302 GET /lab? (@127.0.0.1) 0.66ms\n",
      "[W 2025-05-14 21:14:27.946 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:27.947 ServerApp] 403 GET /api/kernelspecs?1747250067945 (@127.0.0.1) 1.60ms referer=None\n",
      "[W 2025-05-14 21:14:27.948 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:27.949 ServerApp] 403 GET /api/kernels?1747250067945 (@127.0.0.1) 1.24ms referer=None\n",
      "[W 2025-05-14 21:14:27.950 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:27.951 ServerApp] 403 GET /api/kernels?1747250067947 (@127.0.0.1) 1.63ms referer=None\n",
      "[W 2025-05-14 21:14:27.952 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:27.952 ServerApp] 403 GET /api/sessions?1747250067947 (@127.0.0.1) 2.07ms referer=None\n",
      "[W 2025-05-14 21:14:27.955 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:14:27.955 ServerApp] 403 GET /api/kernelspecs?1747250067951 (@127.0.0.1) 0.98ms referer=None\n",
      "[I 2025-05-14 21:15:44.506 ServerApp] 302 GET / (@127.0.0.1) 0.48ms\n",
      "[I 2025-05-14 21:15:44.508 LabApp] 302 GET /lab? (@127.0.0.1) 0.72ms\n",
      "[W 2025-05-14 21:15:44.511 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:15:44.511 ServerApp] 403 GET /api/kernelspecs?1747250144510 (@127.0.0.1) 0.75ms referer=None\n",
      "[W 2025-05-14 21:15:44.512 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:15:44.512 ServerApp] 403 GET /api/kernels?1747250144510 (@127.0.0.1) 0.53ms referer=None\n",
      "[W 2025-05-14 21:15:44.516 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:15:44.517 ServerApp] 403 GET /api/kernels?1747250144512 (@127.0.0.1) 0.95ms referer=None\n",
      "[W 2025-05-14 21:15:44.517 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:15:44.517 ServerApp] 403 GET /api/sessions?1747250144512 (@127.0.0.1) 0.80ms referer=None\n",
      "[W 2025-05-14 21:15:44.518 ServerApp] wrote error: 'Forbidden'\n",
      "    Traceback (most recent call last):\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 1788, in _execute\n",
      "        result = method(*self.path_args, **self.path_kwargs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/tornado/web.py\", line 3289, in wrapper\n",
      "        url = self.get_login_url()\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "      File \"/Users/jan-hendrik/Library/Application Support/Blender/4.4/extensions/.local/lib/python3.11/site-packages/jupyter_server/base/handlers.py\", line 783, in get_login_url\n",
      "        raise web.HTTPError(403)\n",
      "    tornado.web.HTTPError: HTTP 403: Forbidden\n",
      "[W 2025-05-14 21:15:44.518 ServerApp] 403 GET /api/kernelspecs?1747250144515 (@127.0.0.1) 0.55ms referer=None\n",
      "[I 2025-05-14 21:15:46.369 ServerApp] 302 GET / (@127.0.0.1) 0.34ms\n",
      "[I 2025-05-14 21:15:46.370 LabApp] 302 GET /lab? (@127.0.0.1) 0.43ms\n",
      "[I 2025-05-14 21:15:46.403 ServerApp] Kernel started: bc0848c2-fc6f-499a-973b-cd6e98ac57fe\n"
     ]
    }
   ],
   "source": [
    "#On MacOS, if uv is installed via homebrew:\n",
    "import subprocess\n",
    "command = [\n",
    "    \"UV_PYTHON=python3.11\",\n",
    "    \"/opt/homebrew/bin/uv\", \"pip\", \"install\",\n",
    "    \"--prefix\", \"/Applications/Blender.app/Contents/Resources/4.3/python/\",\n",
    "    \"matplotlib\"\n",
    "]\n",
    "subprocess.run(\" \".join(command), shell=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
